server:
  context-path: /s
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/tiku_schedule?characterEncoding=utf8&useSSL=false
    username: root
    password: 123
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
security:
  basic:
    enabled: false
api:
  host: http://192.168.10.26
  prefix: ${api.host}/${server.context-path}/api/
  token: a1608fe464a14a009968857752497a84