server:
  port: 18085

spring:
  application:
    name: ${server_name}
  profiles:
    active: ${project.environment}
  jackson:
    time-zone: GMT+8

feign:
  hystrix:
    enabled: true

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

  http:
    encoding:
      charset: UTF-8
      force: true
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
mybatis:
  configuration:
    map-underscore-to-camel-case: true

mapper:
  enum-as-simple-type: true

management:
  info.git.mode: full
  security:
    enabled: false
  context-path: /_monitor
  add-application-context-header: false

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 4000

htonline:
  wrapper.enabled: true

logging:
  config: "classpath:config/log4j2-${project.environment}.xml"

weChat:
  appId: wxbddb8c3dc3cd8e0a
  secret: df20b770b79237bbcfac4c1cd6e5a2b6
  grantType: authorization_code
  requestUrl: https://api.weixin.qq.com/sns/jscode2session?

---
spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://192.168.100.210:3307/tu_one?characterEncoding=utf8&useSSL=false
    username: root
    password: huatu2017mysqltest1121

logging:
  level:
    com.huatu.ic.tiku.biz: debug

php-schedule.ribbon.listOfServers: http://testapi.huatu.com/lumenapi/

data-report.ribbon.listOfServers: http://123.103.86.52/gss/

php-blue.ribbon.listOfServers: http://blue.htexam.com/

---
spring:
  profiles: test

  datasource:
    url: jdbc:mysql://192.168.100.210:3307/tu_one?characterEncoding=utf8&useSSL=false
    username: root
    password: huatu2017mysqltest1121

php-schedule.ribbon.listOfServers: http://testapi.huatu.com/lumenapi/

data-report.ribbon.listOfServers: http://192.168.100.22/gss/

php-blue.ribbon.listOfServers: http://blue.htexam.com/

---
spring:
  profiles: product

  datasource:
    url: jdbc:mysql://192.168.100.18:3306/tu_one?characterEncoding=utf8&useSSL=false
    username: vhuatu
    password: vhuatu_2013

php-schedule.ribbon.listOfServers: http://api.huatu.com/lumenapi/

data-report.ribbon.listOfServers: http://ns.huatu.com/gss/

php-blue.ribbon.listOfServers: http://blue.htexam.com/