spring:
  datasource:
    url: jdbc:mysql://172.17.70.225:3306/galaxy?characterEncoding=UTF-8&transformedBitIsBoolean=false&tinyInt1isBit=false&autoReconnect=true&useUnicode=true&characterEncoding=utf-8&autoReconnectForPools=true&failOverReadOnly=false&connectTimeout=5000&useSSL=false
    username: galaxy
    password: galaxy@HuaTu2018
  jpa:
    hibernate:
      ddl-auto: update