server:
  port: 8898
  compression:
      enabled: true
      mime-types: application/json,application/xml,text/html,text/xml,text/plain
      min-response-size: 2048
#替换Tomcat容器，性能更优
  undertow:
    io-threads: 8
    worker-threads: 248
    buffer-size: 1024
  servlet:
    context-path: /api
spring:
  ### 项目基本信息
  application:
   #pom中配置
    name: monitor-server
#  session:
#   #### session失效时间 ：1h
#     timeout: 86400
#     store-type: redis
#     redis:
#       namespace: monitor-server
  ### http配置
  http:
    encoding:
      charset: UTF-8
      force: true

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: com.arj.monitor.common.CustomDialect

  ### jackson配置
  jackson:
    serialization:
      write_dates_as_timestamps: false
      fail_on_empty_beans: false
    deserialization:
      fail_on_unknown_properties: false
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: always
#log日志打印颜色支持
  output:
    ansi:
      enabled: always
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.100.21/monitor?characterEncoding=UTF-8
    username: root
    password: unimob@12254ns
    driver-class-name: com.mysql.jdbc.Driver
    druid:
    #属性类型是字符串，通过别名的方式配置扩展插件
      filters: "stat,slf4j"
      #获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁。
      maxWait: 60000
      #有两个含义：
      # 1) Destroy线程会检测连接的间隔时间，如果连接空闲时间大于等于minEvictableIdleTimeMillis则关闭物理连接。
      # 2) testWhileIdle的判断依据，详细看testWhileIdle属性的说明
      timeBetweenEvictionRunsMillis: 60000
      #	连接保持空闲而不被驱逐的最长时间
      minEvictableIdleTimeMillis: 300000
      #是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
      poolPreparedStatements: false
      #用来检测连接是否有效的sql，要求是一个查询语句，常用select ‘x’。如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会起作用。
      validationQuery: "select 'x'"
      monitor:
        loginUsername: root
        loginPassword: root
        enabled: enabled
        reset-enable: true
        druid-stat-view: "/druid/*"
        druid-web-stat-filter: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      maxActive: 2
      initialSize: 1
      minIdle: 1
  redis:
    host: 192.168.100.21
    #password: 7e73af0f75db@Red1s
    port: 6379


logging:
  config: "classpath:config/log4j2-${spring.profiles.active}.xml"
rest:
  wrapper:
   enabled: true

file:
  targetFilePath: /home/residenceFile
  defaultPicture: default-head.png


feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000 # 默认超时时间

management:
  endpoint: 
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  health: 
    rabbit: 
      enabled: false
#中间件相关信息
collect: 
  redis:
    cluster:
      address: redis://192.168.100.110:6379,redis://192.168.100.201:6380,redis://192.168.100.111:6379,redis://192.168.100.202:6380,redis://192.168.100.112:6379,redis://192.168.100.203:6380
    sentinel: 
      address: redis://192.168.100.110:16381,redis://192.168.100.111:16381
      mastername: user-session-master
  rabbitmq: ##MQ info
    address: 192.168.100.137,192.168.100.138,192.168.100.139
    username: rabbitmq_ztk
    password: rabbitmq_ztk
    queue: monitor_queue
  mysql:  
    url: jdbc:mysql://192.168.100.18/vhuatu?characterEncoding=UTF-8&transformedBitIsBoolean=false&tinyInt1isBit=false
    username: vhuatu
    password: vhuatu_2013
  mongodb:
    uri:  mongodb://huatu_ztk:wEXqgk2Q6LW8UzSjvZrs@192.168.100.153:27017,192.168.100.154:27017,192.168.100.155:27017/huatu_ztk
  etcd: 
    uri: http://etcd01:2379,http://etcd02:2379,http://etcd03:2379
  ssdb: 
    masterHost: 192.168.100.111
    masterPort: 8991
    slaveHost: 192.168.100.112 
    slavePort: 8991
  zookeeper:
    address: 192.168.100.110:2181,192.168.100.111:2181,192.168.100.112:2181
    monitorNode:  /dubbo/com.huatu.ztk.user.dubbo.UserDubboService
  server.url: 192.168.100.22


