spring:
  datasource:
    url:  jdbc:mysql://192.168.100.210:3307/galaxy_dev?characterEncoding=UTF-8&transformedBitIsBoolean=false&tinyInt1isBit=false&autoReconnect=true&useUnicode=true&characterEncoding=utf-8&autoReconnectForPools=true&failOverReadOnly=false&connectTimeout=5000&useSSL=false
    username: root
    password: huatu2017mysqltest1121
    hikari:
      maximum-pool-size: 20
      auto-commit: true
      minimum-idle: 300000
      idle-timeout: 20
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
  client:
    serviceUrl:
      defaultZone: http://jbzm:jbzm521@192.168.100.162:10009/eureka
    registry-fetch-interval-seconds: 10

elasticsearch:
  host: 192.168.100.161
  port: 9300
  cluster:
    name: elasticsearch

