// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Knowledge.proto

package com.huatu.ztk.question.protobuf;

public final class KnowledgeProtos {
  private KnowledgeProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface KnowledgeProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:KnowledgeProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated int32 points = 1;</code>
     *
     * <pre>
     *知识点id
     * </pre>
     */
    java.util.List<Integer> getPointsList();
    /**
     * <code>repeated int32 points = 1;</code>
     *
     * <pre>
     *知识点id
     * </pre>
     */
    int getPointsCount();
    /**
     * <code>repeated int32 points = 1;</code>
     *
     * <pre>
     *知识点id
     * </pre>
     */
    int getPoints(int index);

    /**
     * <code>repeated string pointsName = 2;</code>
     *
     * <pre>
     *考点名称
     * </pre>
     */
    com.google.protobuf.ProtocolStringList
        getPointsNameList();
    /**
     * <code>repeated string pointsName = 2;</code>
     *
     * <pre>
     *考点名称
     * </pre>
     */
    int getPointsNameCount();
    /**
     * <code>repeated string pointsName = 2;</code>
     *
     * <pre>
     *考点名称
     * </pre>
     */
    String getPointsName(int index);
    /**
     * <code>repeated string pointsName = 2;</code>
     *
     * <pre>
     *考点名称
     * </pre>
     */
    com.google.protobuf.ByteString
        getPointsNameBytes(int index);
  }
  /**
   * Protobuf type {@code KnowledgeProto}
   */
  public static final class KnowledgeProto extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:KnowledgeProto)
      KnowledgeProtoOrBuilder {
    // Use KnowledgeProto.newBuilder() to construct.
    private KnowledgeProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private KnowledgeProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final KnowledgeProto defaultInstance;
    public static KnowledgeProto getDefaultInstance() {
      return defaultInstance;
    }

    public KnowledgeProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private KnowledgeProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                points_ = new java.util.ArrayList<Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              points_.add(input.readInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                points_ = new java.util.ArrayList<Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                points_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                pointsName_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              pointsName_.add(bs);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          points_ = java.util.Collections.unmodifiableList(points_);
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          pointsName_ = pointsName_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.huatu.ztk.question.protobuf.KnowledgeProtos.internal_static_KnowledgeProto_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.huatu.ztk.question.protobuf.KnowledgeProtos.internal_static_KnowledgeProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.huatu.ztk.question.protobuf.KnowledgeProtos.KnowledgeProto.class, com.huatu.ztk.question.protobuf.KnowledgeProtos.KnowledgeProto.Builder.class);
    }

    public static com.google.protobuf.Parser<KnowledgeProto> PARSER =
        new com.google.protobuf.AbstractParser<KnowledgeProto>() {
      public KnowledgeProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new KnowledgeProto(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<KnowledgeProto> getParserForType() {
      return PARSER;
    }

    public static final int POINTS_FIELD_NUMBER = 1;
    private java.util.List<Integer> points_;
    /**
     * <code>repeated int32 points = 1;</code>
     *
     * <pre>
     *知识点id
     * </pre>
     */
    public java.util.List<Integer>
        getPointsList() {
      return points_;
    }
    /**
     * <code>repeated int32 points = 1;</code>
     *
     * <pre>
     *知识点id
     * </pre>
     */
    public int getPointsCount() {
      return points_.size();
    }
    /**
     * <code>repeated int32 points = 1;</code>
     *
     * <pre>
     *知识点id
     * </pre>
     */
    public int getPoints(int index) {
      return points_.get(index);
    }

    public static final int POINTSNAME_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList pointsName_;
    /**
     * <code>repeated string pointsName = 2;</code>
     *
     * <pre>
     *考点名称
     * </pre>
     */
    public com.google.protobuf.ProtocolStringList
        getPointsNameList() {
      return pointsName_;
    }
    /**
     * <code>repeated string pointsName = 2;</code>
     *
     * <pre>
     *考点名称
     * </pre>
     */
    public int getPointsNameCount() {
      return pointsName_.size();
    }
    /**
     * <code>repeated string pointsName = 2;</code>
     *
     * <pre>
     *考点名称
     * </pre>
     */
    public String getPointsName(int index) {
      return pointsName_.get(index);
    }
    /**
     * <code>repeated string pointsName = 2;</code>
     *
     * <pre>
     *考点名称
     * </pre>
     */
    public com.google.protobuf.ByteString
        getPointsNameBytes(int index) {
      return pointsName_.getByteString(index);
    }

    private void initFields() {
      points_ = java.util.Collections.emptyList();
      pointsName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < points_.size(); i++) {
        output.writeInt32(1, points_.get(i));
      }
      for (int i = 0; i < pointsName_.size(); i++) {
        output.writeBytes(2, pointsName_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < points_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(points_.get(i));
        }
        size += dataSize;
        size += 1 * getPointsList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < pointsName_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(pointsName_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getPointsNameList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.huatu.ztk.question.protobuf.KnowledgeProtos.KnowledgeProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.huatu.ztk.question.protobuf.KnowledgeProtos.KnowledgeProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.huatu.ztk.question.protobuf.KnowledgeProtos.KnowledgeProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.huatu.ztk.question.protobuf.KnowledgeProtos.KnowledgeProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.huatu.ztk.question.protobuf.KnowledgeProtos.KnowledgeProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.huatu.ztk.question.protobuf.KnowledgeProtos.KnowledgeProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.huatu.ztk.question.protobuf.KnowledgeProtos.KnowledgeProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.huatu.ztk.question.protobuf.KnowledgeProtos.KnowledgeProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.huatu.ztk.question.protobuf.KnowledgeProtos.KnowledgeProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.huatu.ztk.question.protobuf.KnowledgeProtos.KnowledgeProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.huatu.ztk.question.protobuf.KnowledgeProtos.KnowledgeProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code KnowledgeProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:KnowledgeProto)
        com.huatu.ztk.question.protobuf.KnowledgeProtos.KnowledgeProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.huatu.ztk.question.protobuf.KnowledgeProtos.internal_static_KnowledgeProto_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.huatu.ztk.question.protobuf.KnowledgeProtos.internal_static_KnowledgeProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.huatu.ztk.question.protobuf.KnowledgeProtos.KnowledgeProto.class, com.huatu.ztk.question.protobuf.KnowledgeProtos.KnowledgeProto.Builder.class);
      }

      // Construct using com.huatu.ztk.question.protobuf.KnowledgeProtos.KnowledgeProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        points_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        pointsName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.huatu.ztk.question.protobuf.KnowledgeProtos.internal_static_KnowledgeProto_descriptor;
      }

      public com.huatu.ztk.question.protobuf.KnowledgeProtos.KnowledgeProto getDefaultInstanceForType() {
        return com.huatu.ztk.question.protobuf.KnowledgeProtos.KnowledgeProto.getDefaultInstance();
      }

      public com.huatu.ztk.question.protobuf.KnowledgeProtos.KnowledgeProto build() {
        com.huatu.ztk.question.protobuf.KnowledgeProtos.KnowledgeProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.huatu.ztk.question.protobuf.KnowledgeProtos.KnowledgeProto buildPartial() {
        com.huatu.ztk.question.protobuf.KnowledgeProtos.KnowledgeProto result = new com.huatu.ztk.question.protobuf.KnowledgeProtos.KnowledgeProto(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          points_ = java.util.Collections.unmodifiableList(points_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.points_ = points_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          pointsName_ = pointsName_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.pointsName_ = pointsName_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.huatu.ztk.question.protobuf.KnowledgeProtos.KnowledgeProto) {
          return mergeFrom((com.huatu.ztk.question.protobuf.KnowledgeProtos.KnowledgeProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.huatu.ztk.question.protobuf.KnowledgeProtos.KnowledgeProto other) {
        if (other == com.huatu.ztk.question.protobuf.KnowledgeProtos.KnowledgeProto.getDefaultInstance()) return this;
        if (!other.points_.isEmpty()) {
          if (points_.isEmpty()) {
            points_ = other.points_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePointsIsMutable();
            points_.addAll(other.points_);
          }
          onChanged();
        }
        if (!other.pointsName_.isEmpty()) {
          if (pointsName_.isEmpty()) {
            pointsName_ = other.pointsName_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensurePointsNameIsMutable();
            pointsName_.addAll(other.pointsName_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.huatu.ztk.question.protobuf.KnowledgeProtos.KnowledgeProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.huatu.ztk.question.protobuf.KnowledgeProtos.KnowledgeProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<Integer> points_ = java.util.Collections.emptyList();
      private void ensurePointsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          points_ = new java.util.ArrayList<Integer>(points_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int32 points = 1;</code>
       *
       * <pre>
       *知识点id
       * </pre>
       */
      public java.util.List<Integer>
          getPointsList() {
        return java.util.Collections.unmodifiableList(points_);
      }
      /**
       * <code>repeated int32 points = 1;</code>
       *
       * <pre>
       *知识点id
       * </pre>
       */
      public int getPointsCount() {
        return points_.size();
      }
      /**
       * <code>repeated int32 points = 1;</code>
       *
       * <pre>
       *知识点id
       * </pre>
       */
      public int getPoints(int index) {
        return points_.get(index);
      }
      /**
       * <code>repeated int32 points = 1;</code>
       *
       * <pre>
       *知识点id
       * </pre>
       */
      public Builder setPoints(
          int index, int value) {
        ensurePointsIsMutable();
        points_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 points = 1;</code>
       *
       * <pre>
       *知识点id
       * </pre>
       */
      public Builder addPoints(int value) {
        ensurePointsIsMutable();
        points_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 points = 1;</code>
       *
       * <pre>
       *知识点id
       * </pre>
       */
      public Builder addAllPoints(
          Iterable<? extends Integer> values) {
        ensurePointsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, points_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 points = 1;</code>
       *
       * <pre>
       *知识点id
       * </pre>
       */
      public Builder clearPoints() {
        points_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList pointsName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensurePointsNameIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          pointsName_ = new com.google.protobuf.LazyStringArrayList(pointsName_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string pointsName = 2;</code>
       *
       * <pre>
       *考点名称
       * </pre>
       */
      public com.google.protobuf.ProtocolStringList
          getPointsNameList() {
        return pointsName_.getUnmodifiableView();
      }
      /**
       * <code>repeated string pointsName = 2;</code>
       *
       * <pre>
       *考点名称
       * </pre>
       */
      public int getPointsNameCount() {
        return pointsName_.size();
      }
      /**
       * <code>repeated string pointsName = 2;</code>
       *
       * <pre>
       *考点名称
       * </pre>
       */
      public String getPointsName(int index) {
        return pointsName_.get(index);
      }
      /**
       * <code>repeated string pointsName = 2;</code>
       *
       * <pre>
       *考点名称
       * </pre>
       */
      public com.google.protobuf.ByteString
          getPointsNameBytes(int index) {
        return pointsName_.getByteString(index);
      }
      /**
       * <code>repeated string pointsName = 2;</code>
       *
       * <pre>
       *考点名称
       * </pre>
       */
      public Builder setPointsName(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePointsNameIsMutable();
        pointsName_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string pointsName = 2;</code>
       *
       * <pre>
       *考点名称
       * </pre>
       */
      public Builder addPointsName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePointsNameIsMutable();
        pointsName_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string pointsName = 2;</code>
       *
       * <pre>
       *考点名称
       * </pre>
       */
      public Builder addAllPointsName(
          Iterable<String> values) {
        ensurePointsNameIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, pointsName_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string pointsName = 2;</code>
       *
       * <pre>
       *考点名称
       * </pre>
       */
      public Builder clearPointsName() {
        pointsName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string pointsName = 2;</code>
       *
       * <pre>
       *考点名称
       * </pre>
       */
      public Builder addPointsNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePointsNameIsMutable();
        pointsName_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:KnowledgeProto)
    }

    static {
      defaultInstance = new KnowledgeProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:KnowledgeProto)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_KnowledgeProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_KnowledgeProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017Knowledge.proto\"4\n\016KnowledgeProto\022\016\n\006p" +
      "oints\030\001 \003(\005\022\022\n\npointsName\030\002 \003(\tB2\n\037com.h" +
      "uatu.ztk.question.protobufB\017KnowledgePro" +
      "tos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_KnowledgeProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_KnowledgeProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_KnowledgeProto_descriptor,
        new String[] { "Points", "PointsName", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
